apiVersion: v1
kind: Service
metadata:
  name: python-hello
  labels:
    app: python-hello
spec:
  type: ClusterIP
  selector:
    app: python-hello
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

